CXX=g++
CXXFLAGS= -std=c++14 -Wall -Wextra

all: day1 day2 day3 day5 day6 day7 day8 day9 day10 day12 day14 day16

day1: day1.cpp
	$(CXX) $< -o $@ $(CXXFLAGS)

day2: day2.cpp
	$(CXX) $< -o $@ $(CXXFLAGS)

day3: day3.cpp
	$(CXX) $< -o $@ $(CXXFLAGS)

# day4: day4.cpp
# 	$(CXX) $< -o $(TARGET_FOLDER)$@ $(CXXFLAGS)

day5: day5.cpp
	$(CXX) $< -o $@ $(CXXFLAGS)

day6: day6.cpp
	$(CXX) $< -o $@ $(CXXFLAGS)

day7: day7.cpp
	$(CXX) $< -o $@ $(CXXFLAGS)

day8: day8.cpp
	$(CXX) $< -o $@ $(CXXFLAGS)

day9: day9.cpp
	$(CXX) $< -o $@ $(CXXFLAGS)

day10: day10.cpp
	$(CXX) $< -o $@ $(CXXFLAGS)

day12: day12.cpp
	$(CXX) $< -o $@ $(CXXFLAGS)

day13: day13.cpp
	$(CXX) $< -o $@ $(CXXFLAGS)

day14: day14.cpp
	$(CXX) $< -o $@ $(CXXFLAGS)

day16: day16.cpp
	$(CXX) $< -o $@ $(CXXFLAGS)
	

.PHONY: clean

clean:
	rm -f day1 day2 day3 day5 day6 day7 day8 day9 day10 day12 day14 day16